app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('auth/login', function(){
	return redirect('login');
});

Route::get('auth/register', function(){
	abort(404);
});

Route::get('password/email', function(){
	abort(404);
});

Route::get('/', 'ProductsController@getIndex');

Route::get('home', 'HomeController@index');

Route::group(['prefix' => 'admin','middleware' => 'admin'], function()
{
	// Route::get('products', 'Admin\ProductsController@index');
	Route::controllers(
		[
			'products' => 'Admin\ProductsController',
			'banners' => 'Admin\BannersController',
			'categories' => 'Admin\CategoriesController',
			'news' => 'Admin\NewsController',
			'analytics' => 'Admin\AnalyticsController'
		]
	);
});

Route::controllers(
	[
		'products' => 'ProductsController',
		'categories' => 'CategoriesController',
		'login' => 'LoginController',
		'members' => 'Admin\MembersController'
	]
);


Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	// protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	protected $guarded = [];

	public function getMembershipTypeAttribute(){
		$index = ((!is_null($this->classification) && MembershipType::MEMBERSHIPS[$this->classification] !== null)?MembershipType::MEMBERSHIPS[$this->classification]:'');
		if(empty($index))
			return '';
			
		return trans("content.".$index);
	}

}

app/Http/Controllers/Admin/MembersController.php
<?php 
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Validator;
use App\NewsInfo;
use Auth;
use App\MembershipType;

class MembersController extends Controller {

    public function __construct()
	{
		$this->middleware('auth');
    }

    public function getIndex(){
        return view('admin.members.index',['user' => Auth::user()]);
    }

}

resources/views/admin/members/index.blade.php
@extends('layouts.public')

@section('content')
            <div class="col-md-6">
                    <h2>会員情報</h2>
                    <p>氏名（姓）: {{$user->lastname}}</p>
                    <p>氏名（名）: {{$user->firstname}}</p>
                    <p>会員種別 : {{$user->membership_type}}</p>
                    <p>会員有効期限 {{date('Y年m月d日',strtotime($user->expiration_date))}}</p>
                    <br/>
                    <p><a class="btn btn-sm btn-primary" href="https://m3.members-support.jp/JapanMap/">会費支払い</a>（カード決済・コンビニ支払いはこちら）</p>
                    <br/>
                    <p>
                    ※ 郵便局から振込支払をご希望の方は事務局までお知らせください。<br/>
                        メール：map-club@jmc.or.jp<br/>
                        電話：03-3485-5417
                        </p>
            </div>
@endsection

@section('styles')
<link href="{{url('public/css/navbar.css')}}" rel="stylesheet">
@endsection